[tool.poetry]
name = "alex_leontiev_toolbox_python"
version = "0.1.0"
description = ""
authors = ["Oleksii Leontiev <alozz1991@gmail.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = ">=3.9"
google-cloud-bigquery = {version="^3.2.0",optional=true}
sqlparse = {version="^0.4.2",optional=true}
SQLAlchemy = {version="^1.4.39",optional=true}
Jinja2 = "^3.1.2"
pandas = ">=2.0.0"
db-dtypes = {version="^1.0.2",optional=true}
tqdm = "^4.64.0"
google-auth-oauthlib = {version="^1.0.0",optional=true}
google-api-python-client = {version="^2.79.0",optional=true}
click = "^8.1.7"
more-itertools = "^10.5.0"
matplotlib = {version="^3.9.2",optional=true}
seaborn = {version="^0.13.2",optional=true}
pandas-gbq = {version="^0.28.0",optional=true}

[tool.poetry.extras]
bigquery=["google-cloud-bigquery","sqlparse",'SQLAlchemy',"db-dtypes","google-auth-oauthlib","google-api-python-client","pandas-gbq"]
analytics=["matplotlib","pandas-gbq"]

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
