"""===============================================================================

        FILE: /Users/nailbiter/Documents/forgithub/alex_leontiev_toolbox_python/tests/test___bigquery__parse_utils.py

       USAGE: (not intended to be directly executed)

 DESCRIPTION: 

     OPTIONS: ---
REQUIREMENTS: ---
        BUGS: ---
       NOTES: ---
      AUTHOR: Alex Leontiev (alozz1991@gmail.com)
ORGANIZATION: 
     VERSION: ---
     CREATED: 2025-01-21T23:31:05.570845
    REVISION: ---

==============================================================================="""
import logging
import unittest
from alex_leontiev_toolbox_python.bigquery.parse_utils import query_to_subqueries


# class TestBigqueryParseUtils(unittest.TestCase):
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self._logger = logging.getLogger(self.__class__.__name__)

#     def test_something(self):
#         self.assertTrue(1 == 1)
#         self.assertEqual(1, 1)
#         self.assertNotEqual(1, 2)

## generated by Gemini
_SAMPLE_SQLS = [
    """WITH CustomerTotalOrders AS (
    SELECT
        c.customer_id,
        c.customer_name,
        COUNT(o.order_id) AS total_orders
    FROM
        `customers` AS c
    LEFT JOIN
        `orders` AS o ON c.customer_id = o.customer_id
    GROUP BY
        c.customer_id, c.customer_name
),

HighValueCustomers AS (
    SELECT
        customer_id,
        customer_name
    FROM
        CustomerTotalOrders
    WHERE
        total_orders > 5
),

OrderTotals AS (
    SELECT
        o.order_id,
        SUM(oi.quantity * oi.unit_price) AS total_amount
    FROM
        `orders` AS o
    LEFT JOIN
        `order_items` AS oi ON o.order_id = oi.order_id
    GROUP BY
        o.order_id
),

OrderedProducts AS (
    SELECT
        oi.order_id,
        ARRAY_AGG(p.product_name) AS products_ordered
    FROM
        `order_items` AS oi
    LEFT JOIN
        `products` AS p ON oi.product_id = p.product_id
    GROUP BY
        oi.order_id
)

SELECT
    o.order_id,
    o.order_date,
    hvc.customer_name,
    ot.total_amount,
    op.products_ordered
FROM
    `orders` AS o
LEFT JOIN
    HighValueCustomers AS hvc ON o.customer_id = hvc.customer_id
LEFT JOIN
    OrderTotals AS ot ON o.order_id = ot.order_id
LEFT JOIN
    OrderedProducts AS op ON o.order_id = op.order_id
    """,
]


def test_query_to_subqueries():
    d = query_to_subqueries(_SAMPLE_SQLS[0], is_loud=True)
    assert set(d.keys()) == {
        "OrderedProducts",
        "OrderTotals",
        "HighValueCustomers",
        "CustomerTotalOrders",
    }
    assert (
        d["OrderedProducts"]
        == """
    SELECT
        oi.order_id,
        ARRAY_AGG(p.product_name) AS products_ordered
    FROM
        `order_items` AS oi
    LEFT JOIN
        `products` AS p ON oi.product_id = p.product_id
    GROUP BY
        oi.order_id
    """.strip()
    )
